# Copied from hrsh7th/nvim-cmp/.github/workflows/format.yaml

name: format

on:
  push:
    branches:
      - '*' # Runs on any branch when changes are pushed
    paths:
      - '**.lua'
  pull_request:
    branches:
      - '*' # Runs when a PR targets any branch
    paths:
      - '**.lua'

permissions:
  contents: write

jobs:
  postprocessing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Format with Stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          version: v0.16.1
          args: 'src/**/*.lua'
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Format with stylua"
