name: Lua Tests

on:
  push:
    branches:
      - '*' # Runs on any branch when changes are pushed
  pull_request:
    branches:
      - '*' # Runs when a PR targets any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Lua and Luarocks
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.4 lua5.4-dev
          curl -R -O http://luarocks.org/releases/luarocks-3.9.1.tar.gz
          tar zxpf luarocks-3.9.1.tar.gz
          cd luarocks-3.9.1
          ./configure --with-lua-include=/usr/include/lua5.4
          make && sudo make install
          cd ..

      - name: Install dependencies
        run: |
          luarocks install busted
          luarocks install luassert
      - name: Run tests
        run: |
          busted src/tests/*.lua  # Adjust the path to where your tests are located
