name: Lua Tests

on:
  push:
    branches:
      - '*' # Runs on any branch when changes are pushed
  pull_request:
    branches:
      - '*' # Runs when a PR targets any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v8
        with:
          lua-version: '5.4'  # Specify Lua version (e.g., 5.1, 5.2, 5.3, 5.4)

      - name: Install dependencies
        run: |
          luarocks install busted
          luarocks install luassert

      - name: Run tests
        run: |
          busted src/tests/*.lua  # Adjust the path to where your tests are located
