name: Lua Tests

on:
  push:
    branches:
      - '*' # Runs on any branch when changes are pushed
  pull_request:
    branches:
      - '*' # Runs when a PR targets any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        run: |
          sh <(curl -L https://nixos.org/nix/install) --no-daemon

      - name: Setup Nix Environment
        run: |
          nix-env -iA nixpkgs.luarocks nixpkgs.busted nixpkgs.luassert

      - name: Run tests
        run: |
          busted src/tests/*.lua
